### Register user with name, email and password
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "john.doe@example.com",
  "password": "123133"
}

### Delete user by ID
DELETE {{BASE_URL}}/users/20
Content-Type: application/json
Authorization: Bearer {{TOKEN}}
